name: Sync Notes
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  download: 
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Pip Install
        run: |
          cd scripts/
          pip install -r requirements.txt

      - name: Sync and Commit
        run: |
          cd scripts/
          rm notes.json
          python main.py
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions-bot@raybb.dev'
          git add notes.json
          git commit -m "automated note sync"
          git push
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
