name: Sync Notes
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  download: 
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Pip Install
        run: |
          cd scripts/
          pip install -r requirements.txt

      - name: Sync
        run: |
          cd scripts/
          python main.py

