name: Sync Notes
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
permissions:
  contents: write

jobs:
  download: 
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'notes'

      - name: Pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Pip Install
        run: |
          cd scripts/
          pip install -r requirements.txt

      - name: Pull
        run: |
          git pull

      - name: Sync
        run: |
          cd scripts/
          python main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: Commit
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions-bot@raybb.dev'
          git add notes.json
          git commit -m "automated note sync"
          git push --set-upstream origin notes
